### ISSUE TITLE
Error:(13, 22) No resource found that matches the given name: attr 'z_depth'.

### ISSUE THREAD

**Issue by tianshaokai** [w9xhc/Hide-Music-Player#3]
缺少文件

**Comment by tianshaokai** [comment]
已经解决了，缺少导入依赖包，已经在studio 里运行起来了，做的不错，要是加入自动下载歌词，边播放边显示歌词 就好了

**Comment by notHide** [comment]
@tianshaokai 本来是做了歌词功能的，『偷』的网易的接口。  但是！网易把接口封杀了……

**Comment by tianshaokai** [comment]
oo 有没有免费的呢？

**Comment by notHide** [comment]
当时做这个的时候是没有免费的，现在不太清楚。  现在精力不在弄播放器上面了，因为工作比较忙，见谅。  以后考虑把歌词界面的源代码放出，其实没有太多技术含量。

**Comment by tianshaokai** [comment]
哈哈，对音乐播放都没怎么做过，对这块不熟悉，希望作者有时间了，可以完善一下让我们学习学习

**Comment by ngawidev** [comment]
Import Android Studio ADD  Build.gradle

apply plugin: 'com.android.application'

repositories {
    maven {
        url "https://jitpack.io"
    }
}

android {
    // something your code...
}

dependencies {
    compile 'com.github.ShogoMizumoto:ZDepthShadowLayout:1.0.4'
}

**Comment by anjing422** [comment]
@tianshaokai 怎么导入到android studio里面啊

**Comment by tianshaokai** [comment]
@anjing422  下载下来直接导入就行了啊，不过这项目两年前了

**Comment by anjing422** [comment]
@tianshaokai  不是说这是eclipse的项目嘛？我就是不知道怎么搞到as里面能够运行测试的那种

**Comment by tianshaokai** [comment]
@anjing422 可以添加Gradle 文件就可以导入了很简单的 ，或者从Studio 里选择ADT项目导入

**Comment by anjing422** [comment]
导入依赖包怎么弄？ @tianshaokai 我按照你说的还是导入不成功，可否把你导入成功的项目发我邮箱？谢谢了

**Comment by tianshaokai** [comment]
@anjing422 等有时间就帮你找找原来导入的项目，如果你着急使用可以加qq1575640686 教教你如何导入
